environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install pipenv
    - pipenv install --dev

build: off

test_script:
    - pipenv run mypy leabra7
    - pipenv run pylint leabra7
    - pipenv run yapf --parallel --recursive --diff leabra7 tests
    - pipenv run pytest
