environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda install conda-build -y
  - conda config --append channels pytorch
  - conda config --append channels conda-forge

build_script:
  - conda-build .

deploy_script:
  - deploy_conda.ps1
