environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install pipenv
    - pipenv install --dev

build: off

test_script:
    - mypy leabra7
    - pylint leabra7
    - yapf --parallel --recursive --diff leabra7 tests
    - pytest
