environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - conda install -y conda-build

build: off

test_script:
    - conda-build .
