package:
  name: leabra7
  version: 0.0.14

source:
  path: ..

requirements:
  host:
    - python=3.6.*

  run:
    - python
    - numpy
    - pandas
    - scipy
    - pytorch

test:
  requires:
    - codecov
    - hypothesis
    - mypy
    - pylint
    - pytest
    - pytest-cov
    - pytest-mock
    - yapf

  source_files:
    - .git
    - .pylintrc
    - leabra7
    - setup.cfg
    - tests

  script_env:
    - TOXENV
    - CI
    - TRAVIS
    - TRAVIS_*
